env:
  browser: true
  es6: true
  greasemonkey: true
extends: 'eslint:recommended'
parser: 'babel-eslint'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-constant-condition:
    - error
    -
      checkLoops: false
  no-var:
    - error
  prefer-const:
    - error
globals:
  _: false
  $: false
