# Allow users to create issues without using a predefined template.
blank_issues_enabled: true

contact_links:
  # Direct users to the documentation before they open an issue.
  - name: AdsBypasser Documentation
    url: https://github.com/adsbypasser/adsbypasser/blob/master/README.md
    about: Check the documentation before creating an issue
