_.register({
  rule: [
    'https://3minx.com/upload/en/*',
    'https://4fuk.me/upload/en/*',
    'https://555fap.com/upload/en/*',
    'https://ai18.pics/upload/en/*',
    'https://anime-jav.com/upload/en/*',
    'https://blackwidof.org/upload/en/*',
    'https://chinese-pics.com/upload/en/*',
    'https://cn-av.com/upload/en/*',
    'https://cnpics.org/upload/en/*',
    'https://cnxx.me/upload/en/*',
    'https://cosplay-xxx.com/upload/en/*',
    'https://cosplay18.pics/upload/en/*',
    'https://fc2ppv.stream/upload/en/*',
    'https://fikfok.net/upload/en/*',
    'https://gofile.download/upload/en/*',
    'https://hentai-sub.com/upload/en/*',
    'https://hentai4f.com/upload/en/*',
    'https://hentaicovid.com/uploads/en/*',
    'https://hentaicovid.org/upload/en/*',
    'https://hentaipig.com/upload/en/*',
    'https://hentaixnx.com/upload/en/*',
    'https://idol69.net/upload/en/*',
    'https://javball.com/upload/en/*',
    'https://javring.com/upload/en/*',
    'https://javsunday.com/upload/en/*',
    'https://kin8-av.com/upload/en/*',
    'https://kin8-jav.com/upload/en/*',
    'https://kr-av.com/upload/en/*',
    'https://ovabee.com/upload/en/*',
    'https://pig69.com/upload/en/*',
    'https://porn-pig.com/upload/en/*',
    'https://porn4f.com/upload/en/*',
    'https://porn4f.org/upload/en/*',
    'https://sweetie-fox.com/upload/en/*',
    'https://xcamcovid.com/upload/en/*',
    'https://xxpics.org/upload/en/*',
  ],
  async ready () {
    const m = $('meta[property="og:image"]');
    await $.openImage(m.content);
  },
});
